# MongoDB 101
:source-highlighter: pygments
:pygments-style: manni
:icons: font
:figure-caption!:

. https://docs.mongodb.com/manual/introduction/[Introduction to MongoDB]
.. https://docs.mongodb.com/manual/reference/mongodb-extended-json/[MongoDB Extended JSON]
. https://docs.mongodb.com/manual/crud/[MongoDB CRUD Operations].

[source,sh]
----
gunzip -c datasets/dostojewski.json.gz \
| mongoimport --host localhost:27017 --drop -d test -c dostojewski

gunzip -c datasets/restaurants.json.gz \
| mongoimport --host localhost:27017 --drop -d test -c restaurants

gunzip -c datasets/pomorskie.json.gz \
| jq --compact-output '{
    place: .properties.miejscowosc,
    street: .properties.ulica,
    zipcode: .properties.kodPocztowy,
    nr: .properties.numerPorzadkowy,
    status: .properties.status,
    geometry,
    admunit: .properties.jednostkaAdmnistracyjna
  }' \
| mongoimport --drop -d test -c pomorskie
----


## Getting Started: Insert

MongoDB adds the `_id` field with an `ObjectId` if `_id` is not present
[source,js]
----
db.inventory.insertMany([
   { item: "journal", qty: 25, status: "A",
       size: { h: 14, w: 21, uom: "cm" }, tags: [ "blank", "red" ] },
   { item: "notebook", qty: 50, status: "A",
       size: { h: 8.5, w: 11, uom: "in" }, tags: [ "red", "blank" ] },
   { item: "paper", qty: 100, status: "D",
       size: { h: 8.5, w: 11, uom: "in" }, tags: [ "red", "blank", "plain" ] },
   { item: "planner", qty: 75, status: "D",
       size: { h: 22.85, w: 30, uom: "cm" }, tags: [ "blank", "red" ] },
   { item: "postcard", qty: 45, status: "A",
       size: { h: 10, w: 15.25, uom: "cm" }, tags: [ "blue" ] }
]);

# mongo hacker helpers
# count indexes
# count collections

count docs
----


## Match

[source,js]
----
db.inventory.find( { status: "D" } )
db.inventory.find( { size: { h: 14, w: 21, uom: "cm" } } )
db.inventory.find( { "size.uom": "in" } )
db.inventory.find( { tags: "red" } )

# db.inventory.help()
db.inventory.drop()
----


## https://docs.mongodb.com/manual/tutorial/update-documents/[Update Documents]

[source,js]
----
db.inventory.insertMany( [
  { item: "canvas", qty: 100, size: { h: 28, w: 35.5, uom: "cm" }, status: "A" },
  { item: "journal", qty: 25, size: { h: 14, w: 21, uom: "cm" }, status: "A" },
  { item: "mat", qty: 85, size: { h: 27.9, w: 35.5, uom: "cm" }, status: "A" },
  { item: "mousepad", qty: 25, size: { h: 19, w: 22.85, uom: "cm" }, status: "P" },
  { item: "notebook", qty: 50, size: { h: 8.5, w: 11, uom: "in" }, status: "P" },
  { item: "paper", qty: 100, size: { h: 8.5, w: 11, uom: "in" }, status: "D" },
  { item: "planner", qty: 75, size: { h: 22.85, w: 30, uom: "cm" }, status: "D" },
  { item: "postcard", qty: 45, size: { h: 10, w: 15.25, uom: "cm" }, status: "A" },
  { item: "sketchbook", qty: 80, size: { h: 14, w: 21, uom: "cm" }, status: "A" },
  { item: "sketch pad", qty: 95, size: { h: 22.85, w: 30.5, uom: "cm" }, status: "A" }
] );

db.inventory.updateOne(
  { item: "paper" },
  {
    $set: { "size.uom": "cm", status: "P" },
    $currentDate: { lastModified: true }
  }
)
db.inventory.find({ item: "paper" })

db.inventory.updateMany(
  { "qty": { $lt: 50 } },
  {
    $set: { "size.uom": "in", status: "P" },
    $currentDate: { lastModified: true }
  }
)
db.inventory.find({ qty: { $lt: 50 } })

db.inventory.find({ item: "paper" })
db.inventory.replaceOne(
  { item: "paper" },
  { item: "paper", instock: [ { warehouse: "A", qty: 60 }, { warehouse: "B", qty: 40 } ] }
)
db.inventory.find({ item: "paper" })

db.inventory.drop()
----

Check this:

. atomicity, document size, upsert option, write acknowledgement
. https://docs.mongodb.com/manual/reference/update-methods/[additional update methods]


## https://docs.mongodb.com/manual/tutorial/remove-documents/[Delete Documents]

[source,js]
----
db.inventory.insertMany( [
  { item: "journal", qty: 25, size: { h: 14, w: 21, uom: "cm" }, status: "A" },
  { item: "notebook", qty: 50, size: { h: 8.5, w: 11, uom: "in" }, status: "P" },
  { item: "paper", qty: 100, size: { h: 8.5, w: 11, uom: "in" }, status: "D" },
  { item: "planner", qty: 75, size: { h: 22.85, w: 30, uom: "cm" }, status: "D" },
  { item: "postcard", qty: 45, size: { h: 10, w: 15.25, uom: "cm" }, status: "A" },
] );

db.inventory.deleteMany({ status : "A" })
db.inventory.deleteOne( { status: "D" } )
----

Check this:

. atomicity, write acknowledgement
. https://docs.mongodb.com/manual/reference/update-methods/[additional delete methods]


## https://docs.mongodb.com/manual/core/bulk-write-operations/[Bulk Write Operations]

MongoDB provides clients the ability to perform write operations in bulk. Bulk
write operations affect a single collection. MongoDB allows applications to
determine the acceptable level of acknowledgement required for bulk write
operations.

[source,js]
----
db.characters.insertMany( [
  { "_id" : 1, "char" : "Brisbane", "class" : "monk", "lvl" : 4 },
  { "_id" : 2, "char" : "Eldon", "class" : "alchemist", "lvl" : 3 },
  { "_id" : 3, "char" : "Meldane", "class" : "ranger", "lvl" : 3 }
] );

try {
  db.characters.bulkWrite(
    [
      { insertOne :
        {
          "document" :
          {
            "_id" : 4, "char" : "Dithras", "class" : "barbarian", "lvl" : 4
          }
        }
      },
      { insertOne :
        {
          "document" :
          {
            "_id" : 5, "char" : "Taeln", "class" : "fighter", "lvl" : 3
          }
        }
      },
      { updateOne :
        {
          "filter" : { "char" : "Eldon" },
          "update" : { $set : { "status" : "Critical Injury" } }
        }
      },
      { deleteOne :
        {
          "filter" : { "char" : "Brisbane"}
        }
      },
      { replaceOne :
        {
          "filter" : { "char" : "Meldane" },
          "replacement" : { "char" : "Tanys", "class" : "oracle", "lvl" : 4 }
        }
      }
    ]
  );
} catch (e) {
   print(e);
}

db.characters.find()
----


## https://docs.mongodb.com/manual/geospatial-queries/[Geospatial Queries]

Legacy Coordinate Pairs.
[source,text]
----
<field>: [ <longitude>, <latitude>  ]
<field>: [ <długość>,   <szerokość> ]

<field>: { <field1>: <longitude>, <field2>: <latitude> }
----

* valid longitude values are between -180 and 180, both inclusive.
* valid latitude values are between -90 and 90 (both inclusive).

Geospatial Indexes: 2dsphere
[source,js]
----
db.collection.createIndex( { <field> : "2dsphere" } )
----

Geospatial Query Operators
[source,js]
----
db.places.insert( {
  name: "Central Park",
  location: { type: "Point", coordinates: [ -73.97, 40.77 ] },
  category: "Parks"
} );
db.places.insert( {
  name: "Sara D. Roosevelt Park",
  location: { type: "Point", coordinates: [ -73.9928, 40.7193 ] },
  category: "Parks"
} );
db.places.insert( {
  name: "Polo Grounds",
  location: { type: "Point", coordinates: [ -73.9375, 40.8303 ] },
  category: "Stadiums"
} );

db.places.createIndex( { location: "2dsphere" } )

db.places.find(
  {
    location:
      { $near:
        {
          $geometry: { type: "Point",  coordinates: [ -73.9667, 40.78 ] },
          $minDistance: 1000,
          $maxDistance: 5000
        }
      }
   }
);
----


### https://docs.mongodb.com/manual/tutorial/geospatial-tutorial/[Find Restaurants with Geospatial Queries]

Download the example datasets from:

* https://raw.githubusercontent.com/mongodb/docs-assets/geospatial/neighborhoods.json[neighborhoods]
* https://raw.githubusercontent.com/mongodb/docs-assets/geospatial/restaurants.json[restaurants]

Import these collections into the test database, and create geospatial indexes:
[source,js]
.mongo
----
# db.myColl.createIndex(
#  { score: 1, price: 1, category: 1 },
#  { collation: { locale: "fr" } }
# )

db.restaurants.createIndex({ location: "2dsphere" })
db.neighborhoods.createIndex({ geometry: "2dsphere" })

db.restaurants.findOne()
db.neighborhoods.findOne()
----

[NOTE]
====
. https://docs.mongodb.com/manual/reference/geojson/[GeoJSON Objects]
. http://geojson.io/[geojson.io]
. http://geojsonlint.com[geojsonlint.com] – validates and views your GeoJSON
. https://google-developers.appspot.com/maps/documentation/utils/geojson/[simple GeoJSON editor]
====


## Indexes

. https://docs.mongodb.com/manual/core/crud/[Query Plan, Performance, and Analysis]


## To be cont.

* https://docs.mongodb.com/manual/aggregation/[Aggregation].
