# Deploy a Replica Set for Testing and Development
:source-highlighter: pygments
:pygments-style: manni
:icons: font
:figure-caption!:

[NOTE]
http://gist.asciidoctor.org/?github-egzamin%2Fnosql%2F%2Freplica_sets%2FREADME.adoc[HTML version of this document]

[IMPORTANT]
This tutorial describes how to create a three-member replica set from three
existing mongod instances running with access control disabled.

[NOTE]
====
We are going to rename tabs names in *iTerm2* terminal.
It is convenient to do renaming on the command line.
To make it possible we install the _iterm2-tab-set_ package.
[source,sh]
npm install -g iterm2-tab-set
tabset carbon-1
====

## Replica Set on _localhost_

* https://docs.mongodb.com/manual/tutorial/deploy-replica-set-for-testing[Deploy a Replica Set for Testing and Development].

In empty directory create the necessary directories:
[source,sh]
----
mkdir -p carbon
cd carbon
mkdir -p data-{1,2,3}
----

Start _mongod_ instances, within _carbon_ folder, in their own shell windows:
[source,sh]
----
mongod --port 27001 --replSet carbon --dbpath data-1 --bind_ip localhost --oplogSize 128 \
  --wiredTigerJournalCompressor zlib --wiredTigerCollectionBlockCompressor zlib
mongod --port 27002 --replSet carbon --dbpath data-2 --bind_ip localhost --oplogSize 128 \
  --wiredTigerJournalCompressor zlib --wiredTigerCollectionBlockCompressor zlib
mongod --port 27003 --replSet carbon --dbpath data-3 --bind_ip localhost --oplogSize 128 \
  --wiredTigerJournalCompressor zlib --wiredTigerCollectionBlockCompressor zlib
----
We named our replica set *carbon*.

Read https://docs.mongodb.com/manual/core/replica-set-members[Replica Set Members].

Connect to one of your mongod instances through the mongo shell:
[source,sh]
----
mongo --host localhost:27001
# mongo --host localhost:27001 --shell repl_set_init.js
----

In the fourth terminal tab in the *_mongo_ shell* issue these commands:
[source,js]
.repl_set_init.js
----
rsconf = {
  _id: "carbon",
  members: [
    { _id: 0, host: "localhost:27001" },
    { _id: 1, host: "localhost:27002" },
    { _id: 2, host: "localhost:27003" }
   ]
}
----

Display the current replica configuration:
[source,js]
----
// rs.help()
rs.initiate(rsconf)
rs.conf()
----

Check the status of your replica set at any time with the `rs.status()` operation:
[source,js]
----
rs.status()
----
Check which mongod instance is the PRIMARY.

Now, read https://docs.mongodb.com/manual/applications/replication/[Replica Set Read and Write Semantics].

1. Display the default write concern:
[source,js]
----
cfg = rs.conf()
cfg.settings.getLastErrorDefaults
// these settings slows down writes and replication considerably
// cfg.settings.getLastErrorDefaults = { w: "majority", wtimeout: 1000 }
// rs.reconfig(cfg)
----
We can always modify it later.

2. https://docs.mongodb.com/manual/core/read-preference[Read Preference].
Change read preference mode to: **secondary** – all operations read from
the secondary members of the replica set.

The syntax for specifying the read preference mode
https://api.mongodb.com[is specific to the driver and to the idioms of the host language].

In the _mongo_ shell, the `readPref()` cursor method provides access
to read preferences:
[source,js]
----
cursor.readPref("secondary")
----

## Importing data into Replica Set

- [x] export Dostojewski to JSON

[source,sh]
.Terminal
----
mongoexport --port 27002 -c dostojewski | gzip -c > dostojewski.json.gz
gunzip -c datasets/dostojewski.json.gz | \
  mongoimport --host carbon/localhost:27001,localhost:27002,localhost:27003 \
  -d test -c dostojewski --drop
----


## Connecting to SECONDARIES

[source,sh]
.Terminal
----
mongo --quiet --host localhost:27003 # assume that this host is SECONDARY
----
[source,js]
.mongo SECONDARY
----
rs.slaveOk()
show dbs
show collections
count docs # defined by mongo-hacker
----


## Replica Set in lab 109






.
